server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      schema-locations: classpath:sql/schema.sql
#      data-locations: classpath:sql/data.sql
      mode: always

  jpa:
    hibernate:
      ddl-auto=update:

logging:
  level:
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.aop: DEBUG
#    org.springframework.transaction.support: TRACE

#debug: true
