server:
  port: 8081

minio:
  url: http://localhost:9000
  access-key: minio_user
  secret-key: password123
  bucket-name: "photo-bucket"

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}



  liquibase:
    change-log: classpath:db/liquibase/liquibase-changelog.yaml
  #  sql:
  #    init:
  #      schema-locations: classpath:sql/schema.sql
  ##      data-locations: classpath:sql/data.sql
  #      mode: always

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.aop: DEBUG
#    org.springframework.transaction.support: TRACE

#debug: true
